tunnel: b7f60d36-f98a-4f69-bcc6-d7524604d484
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Main domain - points to nginx (serves React app and proxies /api to app-wireguard)
  - hostname: grapevine.co.ke
    service: http://react:3000

  # www subdomain
  - hostname: www.grapevine.co.ke
    service: http://react:3000

  # API subdomain
  - hostname: api.grapevine.co.ke
    service: http://app-wireguard:5000

  - hostname: portal.grapevine.co.ke
    service: http://react:3000
  # VPN admin interface
  - hostname: vpn.grapevine.co.ke
    service: udp://app-wireguard:51820

  # Catch-all for any other subdomains
  - hostname: "*.grapevine.co.ke"
    service: http://react:3000


  # Required catch-all rule (must be last)
  - service: http_status:404

# Optional configurations
loglevel: info
retries: 5
grace-period: 30s