tunnel: b7f60d36-f98a-4f69-bcc6-d7524604d484
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Main domain - points to nginx (serves React app and proxies /api to node)
  - hostname: grapevine.co.ke
    service: http://nginx:80
    originRequest:
      originServerName: grapevine.co.ke
      noTLSVerify: false
      disableChunkedEncoding: true
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  # www subdomain
  - hostname: www.grapevine.co.ke
    service: http://nginx:80
    originRequest:
      originServerName: www.grapevine.co.ke
      noTLSVerify: false
      disableChunkedEncoding: true
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  # API subdomain
  - hostname: api.grapevine.co.ke
    service: http://node:5000
    originRequest:
      originServerName: api.grapevine.co.ke
      noTLSVerify: false
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  # VPN admin interface
  - hostname: vpn.grapevine.co.ke
    service: udp://node:51820
    originRequest:
      noTLSVerify: false
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  - hostname: radius.grapevine.co.ke
    service: udp://node:1812
    originRequest:
      noTLSVerify: false
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  - hostname: radius-acct.grapevine.co.ke
    service: udp://node:1813
    originRequest:
      noTLSVerify: false
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  # Catch-all for any other subdomains
  - hostname: "*.grapevine.co.ke"
    service: http://nginx:80
    originRequest:
      originServerName: grapevine.co.ke
      noTLSVerify: false
      disableChunkedEncoding: true
      http2Origin: true
      proxyTcpKeepalive: 30s
      proxyNoHappyEyeballs: false
      proxyKeepaliveConnections: 100
      proxyKeepaliveTimeout: 90s

  # Required catch-all rule (must be last)
  - service: http_status:404

# Optional configurations
loglevel: info
retries: 5
grace-period: 30s